---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  MOVIE_APP_URL:

inputs:
- name: apps-movie-fun-code-source

run:
  path: apps-movie-fun-code-source/ci/tasks/smoke-test.sh
